/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_accept[177] =
    {   0,
        0,    0,    0,    0,    0,    0,    7,    7,    0,    0,
        0,    0,   62,   61,   27,    1,   39,   41,   31,   38,
       58,   39,   34,   34,   57,   31,   28,   35,   36,   35,
       40,   38,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   38,   51,   43,   42,   61,    3,    5,    3,
        7,    9,    8,   60,   59,   27,   35,   37,   58,   58,
        0,   32,   33,   29,    6,    2,   29,   28,   54,   54,
       38,   40,   40,   40,   40,   40,   40,   13,   40,   40,
       40,   11,   40,   40,   40,   40,   40,   51,   50,   44,
       48,   49,   45,   47,   46,    4,    7,    8,    8,   10,

        0,   30,   58,    0,    0,    0,   58,    0,    0,    0,
        0,   29,    0,   29,   28,   54,    0,    0,   29,   40,
       40,   40,   40,   40,   40,   40,   40,   12,   14,   40,
       40,   40,   40,   44,    0,   56,    0,   55,   30,    0,
       52,   52,   29,   29,   53,   40,   25,   22,   40,   40,
       40,   19,   40,   40,   40,   16,   40,    0,   52,   21,
       40,   40,   40,   15,   40,   40,   20,   40,   40,   23,
       24,   17,   40,   18,   26,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   24,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,   26,   27,   28,   29,    1,   30,   31,   32,   33,

       34,   35,   23,   36,   37,   23,   38,   39,   23,   40,
       41,   23,   23,   42,   43,   44,   45,   46,   47,   23,
       23,   23,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    5,    1,    1,
        6,    1,    1,    1,    7,    1,    8,    8,    1,    1,
        1,    1,    9,    9,    1,   10,    1,    1,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1
    } ;

static yyconst short int yy_base[194] =
    {   0,
        0,    0,   48,   49,   52,   53,   54,   55,  411,  410,
        0,    0,  412,  415,  409,  415,  389,  415,  415,  402,
       56,  415,  396,  393,   43,   51,   53,   52,  385,   59,
        0,  415,  363,   53,   35,  365,   45,   50,  369,  355,
      360,  364,  350,    0,  415,  415,   70,  415,  415,  394,
        0,  415,   80,  415,  415,  394,  415,  415,  415,   90,
      116,  415,  415,   82,  415,  415,  152,  156,    0,  167,
      415,    0,  361,  348,  360,  349,  352,  341,  339,  340,
      338,    0,  335,  334,  340,  334,  333,    0,  415,   85,
      415,  415,  415,  415,  415,  415,    0,   93,   97,  415,

      166,  415,  175,  156,  361,  359,  349,  186,  187,  191,
      180,  190,  192,  201,  205,    0,  209,  213,  217,  320,
      313,  287,  284,  288,  286,  282,  284,    0,    0,  216,
      216,  226,  219,  219,  213,  415,  249,  415,  415,  236,
      223,  225,  230,  232,  234,  215,    0,    0,  209,  188,
      189,    0,  180,  169,  171,    0,  166,  182,  238,    0,
      146,  136,  138,    0,   75,   75,    0,   62,   51,    0,
        0,    0,   29,    0,    0,  415,  262,  272,  282,  292,
      302,  310,  314,  316,  325,  334,  344,  354,  363,  366,
      374,  383,  389

    } ;

static yyconst short int yy_def[194] =
    {   0,
      176,    1,  177,  177,  178,  178,  179,  179,  180,  180,
      181,  181,  176,  176,  176,  176,  176,  176,  176,  176,
      182,  176,  176,  176,  176,  176,  183,  176,  176,  176,
      184,  176,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  176,  185,  176,  176,  186,  176,  176,  176,
      187,  176,  188,  176,  176,  176,  176,  176,  176,  189,
      176,  176,  176,  176,  176,  176,  176,  183,  190,  190,
      176,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  185,  176,  176,
      176,  176,  176,  176,  176,  176,  187,  188,  188,  176,

      191,  176,  189,  176,  176,  176,  176,  192,  192,  192,
      176,  176,  176,  176,  183,  190,  176,  176,  190,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  176,  191,  176,  193,  176,  176,  192,
      176,  176,  176,  176,  176,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  193,  176,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,    0,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176

    } ;

static yyconst short int yy_nxt[466] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       19,   23,   22,   24,   25,   26,   27,   27,   22,   28,
       29,   30,   31,   31,   22,   14,   22,   32,   31,   31,
       33,   34,   35,   36,   37,   31,   38,   31,   31,   31,
       31,   39,   40,   31,   31,   41,   42,   22,   43,   22,
       45,   45,   46,   46,   49,   49,   52,   52,   59,   64,
       64,   65,  175,   59,   53,   53,   66,   67,   77,   68,
       68,   71,   57,   47,   47,   78,   70,   50,   50,   57,
       71,   61,   74,   80,   82,   81,   90,   90,   75,   83,
       99,  101,   59,   76,  174,  100,  111,  102,  112,  112,

       91,  134,  134,  176,   92,  113,  173,   99,  176,   93,
      172,   94,  100,   95,  171,  104,  105,  105,  105,  105,
      106,  105,  105,  107,  105,  105,  105,  105,  105,  105,
      105,  105,  106,  105,  105,  105,  105,  105,  108,  108,
      105,  106,  105,  105,  105,  109,  110,  108,  108,  108,
      110,  108,  108,  108,  108,  110,  108,  109,  108,  110,
      108,  110,  108,  105,  105,  105,  111,  101,  112,  112,
      114,  170,  115,  115,  169,  113,  101,   59,  117,   70,
      117,  118,  136,  119,  119,  168,  137,  101,  101,  136,
      137,  104,  101,  138,  139,  137,  141,  141,  102,  167,

      104,  137,  166,  117,  142,  117,  143,  143,  144,  144,
      165,  104,  104,  113,  176,  111,  104,  143,  143,  114,
      136,  115,  115,  164,  113,  144,  144,  163,   70,  145,
      145,  118,  162,  119,  119,  134,  134,  101,  176,  159,
      159,  159,  159,  136,  142,  161,  143,  143,  144,  144,
      145,  145,  160,  113,  159,  159,  136,  157,  156,  155,
      154,  104,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   60,  153,   60,  152,  151,  150,   60,   60,
       69,   69,   69,   72,   72,   88,   88,  149,  148,   88,
       88,   88,   88,   88,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   97,   97,  147,   97,   97,  146,
       97,   97,   97,   97,   98,   98,  138,   98,   98,   98,
       98,   98,   98,   98,  103,  103,  139,  103,  138,  133,
      132,  103,  103,  116,  116,  135,  131,  130,  129,  128,
      127,  126,  135,  135,  140,  125,  124,  140,  123,  122,
      121,  140,  140,  158,  120,   56,   96,  158,   58,   87,

       86,   85,   84,   79,   73,   57,   63,   62,   58,   57,
       56,  176,   55,   55,   13,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176
    } ;

static yyconst short int yy_chk[466] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,    7,    8,   21,   25,
       25,   26,  173,   21,    7,    8,   26,   27,   35,   27,
       27,   28,   28,    3,    4,   35,   27,    5,    6,   30,
       30,   21,   34,   37,   38,   37,   47,   47,   34,   38,
       53,   60,   60,   34,  169,   53,   64,   60,   64,   64,

       47,   90,   90,   98,   47,   64,  168,   99,   98,   47,
      166,   47,   99,   47,  165,   60,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   67,  101,   67,   67,
       68,  163,   68,   68,  162,   67,  103,  103,   70,   68,
       70,   70,  103,   70,   70,  161,  104,  108,  109,  158,
      104,  101,  110,  108,  109,  104,  111,  111,  110,  157,

      103,  104,  155,  113,  112,  113,  112,  112,  113,  113,
      154,  108,  109,  112,  135,  114,  110,  114,  114,  115,
      135,  115,  115,  153,  114,  117,  117,  151,  115,  118,
      118,  119,  150,  119,  119,  134,  134,  140,  135,  141,
      141,  142,  142,  140,  143,  149,  143,  143,  144,  144,
      145,  145,  146,  143,  159,  159,  137,  133,  132,  131,
      130,  140,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  182,  127,  182,  126,  125,  124,  182,  182,
      183,  183,  183,  184,  184,  185,  185,  123,  122,  185,
      185,  185,  185,  185,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  187,  187,  121,  187,  187,  120,
      187,  187,  187,  187,  188,  188,  107,  188,  188,  188,
      188,  188,  188,  188,  189,  189,  106,  189,  105,   87,
       86,  189,  189,  190,  190,  191,   85,   84,   83,   81,
       80,   79,  191,  191,  192,   78,   77,  192,   76,   75,
       74,  192,  192,  193,   73,   56,   50,  193,   43,   42,

       41,   40,   39,   36,   33,   29,   24,   23,   20,   17,
       15,   13,   10,    9,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1505010.l"
#define INITIAL 0
#line 2 "1505010.l"
#define YYSTYPE SymbolInfo*
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<iostream>

#include "1505010.h"
#include "y.tab.h"
//#define YYSTYPE SymbolInfo*
int MAX_STR_CONST = 1000;
char *string_buf_ptr;
char *tokStr;
int line_num = 1;
int error = 0;
int prevline = 0;
FILE *logout;
FILE *tokenout;
//SymbolTable *sym; // = new SymbolTable;
//#include "SymbolTable.h"
//#include "SymbolInfo.h"

using namespace std;

extern YYSTYPE yylval;
extern SymbolTable *table;
extern FILE *fp2;
void yyerror(char *);

#define str 1

#define cmnt 2

#define comment 3

#define test 4

#define multichar 5

#line 569 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 45 "1505010.l"

#line 733 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 177 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 415 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "1505010.l"
{line_num++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "1505010.l"
{
	string_buf_ptr = (char*) malloc(MAX_STR_CONST * sizeof(char));
	char *ch = (char*) malloc(sizeof(char)*2); 
	//ch = '/';
	strcpy(string_buf_ptr, "//");
	prevline = line_num;
	BEGIN(cmnt);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "1505010.l"
{
	char *yptr = yytext;
	if(strlen(yptr)>MAX_STR_CONST)
	{	
		MAX_STR_CONST += strlen(yptr);
		MAX_STR_CONST*=2;
		string_buf_ptr = (char*) realloc(string_buf_ptr, MAX_STR_CONST);
	}
	strcat(string_buf_ptr, yptr);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "1505010.l"
{
	line_num++;
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "\\\n";
	strcat(string_buf_ptr, "\\\n");
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "1505010.l"
{
	//error++; 
	//printf("Single Comment\n");
	line_num++;
	//fprintf(tokenout,"<COMMENT,%s>\n",string_buf_ptr);
	fprintf(logout,"Line No. %d: Token <COMMENT> Lexeme %s found\n\n",prevline,string_buf_ptr);
	free(string_buf_ptr);
	BEGIN(INITIAL);
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "1505010.l"
{
	string_buf_ptr = (char*) malloc(MAX_STR_CONST * sizeof(char));
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "/*";
	strcpy(string_buf_ptr, "/*");
	prevline = line_num;
	//printf("comment begin\n");
	BEGIN(comment);
	
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "1505010.l"
{
	/* eat anything that's not a '*' */
	char *yptr = yytext;
	if(strlen(yptr)>MAX_STR_CONST)
	{	
		MAX_STR_CONST += strlen(yptr);
		MAX_STR_CONST*=2;
		string_buf_ptr = (char*) realloc(string_buf_ptr, MAX_STR_CONST);
	}
	strcat(string_buf_ptr, yptr);
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "1505010.l"
{
		/* eat up '*'s not followed by '/'s */
	char *yptr = yytext;
	if(strlen(yptr)>MAX_STR_CONST)
	{	
		MAX_STR_CONST += strlen(yptr);
		MAX_STR_CONST*=2;
		string_buf_ptr = (char*) realloc(string_buf_ptr, MAX_STR_CONST);
	}
	strcat(string_buf_ptr, yptr);
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 116 "1505010.l"
{
		line_num++;
		char *ch = (char*) malloc(sizeof(char)); 
		//ch = "\n"; 
		strcat(string_buf_ptr, "\n");
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "1505010.l"
{
		//printf("comment End\n"); 
		char *yptr = yytext;
		strcat(string_buf_ptr, yptr);
		//fprintf(tokenout,"<COMMENT,%s>\n",string_buf_ptr);
		fprintf(logout,"Line No. %d: Token <COMMENT> Lexeme %s found\n\n",prevline,string_buf_ptr);
		free(string_buf_ptr);
		BEGIN(INITIAL);
	}
	YY_BREAK
case YY_STATE_EOF(comment):
#line 131 "1505010.l"
{
		fprintf(logout,"Error at line %d: Unfinished comment %s\n\n",line_num,string_buf_ptr);
		error++;
		free(string_buf_ptr);
		//printf("comment begin\n");
		BEGIN(INITIAL);

	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "1505010.l"
{
	//printf("<IF>");
	fprintf(tokenout,"<IF>  ");
	fprintf(logout,"Line No. %d: Token <IF> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"IF");
	yylval = (YYSTYPE)s;
	return IF;
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 147 "1505010.l"
{
	//printf("<FOR>");
	fprintf(tokenout,"<FOR>  ");
	fprintf(logout,"Line No. %d: Token <FOR> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"FOR");
	yylval = (YYSTYPE)s;
	return FOR;
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "1505010.l"
{
	//printf("<DO>");
	fprintf(tokenout,"<DO>  ");
	fprintf(logout,"Line No. %d: Token <DO> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"DO");
	yylval = (YYSTYPE)s;
	return DO;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 163 "1505010.l"
{
	//printf("<INT>");
	fprintf(tokenout,"<INT>  ");
	fprintf(logout,"Line No. %d: Token <INT> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"INT");
	yylval = (YYSTYPE)s;
	//cout << "\n\nyylval: " << yylval->getName() <<endl <<endl;
	return INT;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 172 "1505010.l"
{
	//printf("<FLOAT>");
	fprintf(tokenout,"<FLOAT>  ");
	fprintf(logout,"Line No. %d: Token <FLOAT> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"FLOAT");
	yylval = (YYSTYPE)s;
	return FLOAT;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 180 "1505010.l"
{
	//printf("<VOID>");
	fprintf(tokenout,"<VOID>  ");
	fprintf(logout,"Line No. %d: Token <VOID> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"VOID");
	yylval = (YYSTYPE)s;
	return VOID;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 188 "1505010.l"
{
	//printf("<SWITCH>");
	fprintf(tokenout,"<SWITCH>  ");
	fprintf(logout,"Line No. %d: Token <SWITCH> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"SWITCH");
	yylval = (YYSTYPE)s;
	return SWITCH;
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 196 "1505010.l"
{
	//printf("<DEFAULT>");
	fprintf(tokenout,"<DEFAULT>  ");
	fprintf(logout,"Line No. %d: Token <DEFAULT> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"DEFAULT");
	yylval = (YYSTYPE)s;
	return DEFAULT;
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 204 "1505010.l"
{
	//printf("<ELSE>");
	fprintf(tokenout,"<ELSE>  ");
	fprintf(logout,"Line No. %d: Token <ELSE> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"ELSE");
	yylval = (YYSTYPE)s;
	return ELSE;
	
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 213 "1505010.l"
{
	//printf("<WHILE>");
	fprintf(tokenout,"<WHILE>  ");
	fprintf(logout,"Line No. %d: Token <WHILE> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"WHILE");
	yylval = (YYSTYPE)s;
	return WHILE;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 221 "1505010.l"
{
	//printf("<BREAK>");
	fprintf(tokenout,"<BREAK>  ");
	fprintf(logout,"Line No. %d: Token <BREAK> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"BREAK");
	yylval = (YYSTYPE)s;
	return BREAK;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 229 "1505010.l"
{
	//printf("<CHAR>");
	fprintf(tokenout,"<CHAR>  ");
	fprintf(logout,"Line No. %d: Token <CHAR> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"CHAR");
	yylval = (YYSTYPE)s;
	return CHAR;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 237 "1505010.l"
{
	//printf("<DOUBLE>");
	fprintf(tokenout,"<DOUBLE>  ");
	fprintf(logout,"Line No. %d: Token <DOUBLE> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"DOUBLE");
	yylval = (YYSTYPE)s;
	return DOUBLE;
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 245 "1505010.l"
{
	//printf("<RETURN>");
	fprintf(tokenout,"<RETURN>  ");
	fprintf(logout,"Line No. %d: Token <RETURN> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"RETURN");
	yylval = (YYSTYPE)s;
	return RETURN;
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 253 "1505010.l"
{
	//printf("<CASE>");
	fprintf(tokenout,"<CASE>  ");
	fprintf(logout,"Line No. %d: Token <CASE> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"CASE");
	yylval = (YYSTYPE)s;
	return CASE;
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 261 "1505010.l"
{
	//printf("<CONTINUE>");
	fprintf(tokenout,"<CONTINUE>  ");
	fprintf(logout,"Line No. %d: Token <CONTINUE> Lexeme %s found\n\n",line_num,yytext);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"CONTINUE");
	yylval = (YYSTYPE)s;
	return CONTINUE;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 269 "1505010.l"
{}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 270 "1505010.l"
{
	//printf("<%s CONST_INT>\n", yytext);
	fprintf(tokenout,"<CONST_INT,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <CONST_INT> Lexeme %s found\n\n",line_num,yytext);
	
	/*
	
	sym->insert(yytext, "CONST_INT");
	sym->printCurScope(logout);
	
	*/
	SymbolInfo *s= new SymbolInfo(yytext, (char *)"CONST_INT");
	yylval = (YYSTYPE)s;
	return CONST_INT;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 285 "1505010.l"
{
	//printf("<%s CONST_FLOAT>\n", yytext);
	fprintf(tokenout,"<CONST_FLOAT,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <CONST_FLOAT> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_FLOAT");
	sym->printCurScope(logout);
	
	*/
	SymbolInfo *s= new SymbolInfo(yytext, (char *)"CONST_FLOAT");
	yylval = (YYSTYPE)s;
	return CONST_FLOAT;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 299 "1505010.l"
{
	switch(yytext[2])
	{
	
	case 'n' : //printf("<CONST_CHAR %c>\n", 10);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",10);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 't' : //printf("<CONST_CHAR %c>\n", 9);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",9);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case '\\' : //printf("\n<CONST_CHAR %c>\n", 92);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",92);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case '"' : //printf("<CONST_CHAR %c>\n", 34);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",34);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 'a' : //printf("<CONST_CHAR %c>\n", 7);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",7);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 'f' : //printf("<CONST_CHAR %c>\n", 12);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",12);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 'r' : //printf("<CONST_CHAR %c>\n", 13);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",13);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 'b' : //printf("<CONST_CHAR %c>\n", 8);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",8);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case 'v' : //printf("<CONST_CHAR %c>\n", 11);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",11);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;
	
	case '0' : //printf("<CONST_CHAR %c>\n", 0);	
	fprintf(tokenout,"<CONST_CHAR,%c>  ",0);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);
	
	*/
	break;

	}

	if(yytext[1]!='\\')
	{
	//printf("<CONST_CHAR, %c>\n", yytext[1]);
	fprintf(tokenout,"<CONST_CHAR,%c>  ",yytext[1]);
	fprintf(logout,"Line No. %d: Token <CONST_CHAR> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	sym->insert(yytext, "CONST_CHAR");
	sym->printCurScope(logout);	
	
	*/
	SymbolInfo *s= new SymbolInfo((char*) yytext[1], (char *)"CONST_CHAR");
	yylval = (YYSTYPE)s;
	return CONST_CHAR;
	}
	SymbolInfo *s= new SymbolInfo(yytext, (char *)"CONST_CHAR");
	yylval = (YYSTYPE)s;
	return CONST_CHAR;	
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 434 "1505010.l"
{
	//printf("<MULOP %s>\n",yytext);
	fprintf(tokenout,"<MULOP,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <MULOP> Lexeme %s found\n\n",line_num,yytext);
	//sym->insert(yytext, "MULOP");
	//sym->printCurScope(logout);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"MULOP");
	yylval = (YYSTYPE)s;
	return MULOP;
	
	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 445 "1505010.l"
{
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"INCOP");
	yylval = (YYSTYPE)s;
	return INCOP;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 450 "1505010.l"
{
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"DECOP");
	yylval = (YYSTYPE)s;	
	return DECOP;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 455 "1505010.l"
{
		//printf("<ADDOP, %s>\n", yytext);
		fprintf(tokenout,"<ADDOP,%s>  ",yytext);
		fprintf(logout,"Line No. %d: Token <ADDOP> Lexeme %s found\n\n",line_num,yytext);
		//sym->insert(yytext, "ADDOP");
		//sym->printCurScope(logout);
		SymbolInfo *s= new  SymbolInfo(yytext, (char *)"ADDOP");
		yylval = (YYSTYPE)s;
		return ADDOP;
			
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 466 "1505010.l"
{
	//printf("<RELOP, %s>\n",yytext);
	fprintf(tokenout,"<RELOP,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <RELOP> Lexeme %s found\n\n",line_num,yytext);
	//sym->insert(yytext, "RELOP");
	//sym->printCurScope(logout);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"RELOP");
	yylval = (YYSTYPE)s;
	return RELOP;
	
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 477 "1505010.l"
{ 
	//printf("<ASSIGNOP, %s>\n", yytext); 
	fprintf(tokenout,"<ASSIGNOP,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <ASSIGNOP> Lexeme %s found\n\n",line_num,yytext);
	//sym->insert(yytext, "ASSIGNOP");
	//sym->printCurScope(logout);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"ASSIGNOP");
	yylval = (YYSTYPE)s;
	return ASSIGNOP;
	
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 488 "1505010.l"
{
	//printf("<LOGICOP, %s>\n", yytext);
	fprintf(tokenout,"<LOGICOP,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <LOGICOP> Lexeme %s found\n\n",line_num,yytext);
	//sym->insert(yytext, "LOGICOP");
	//sym->printCurScope(logout);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"LOGICOP");
	yylval = (YYSTYPE)s;
	return LOGICOP;
	
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 499 "1505010.l"
{ 
	//printf("<BITOP, %s>\n", yytext); 
	fprintf(tokenout,"<BITOP,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <BITOP> Lexeme %s found\n\n",line_num,yytext);
	//sym->insert(yytext, "BITOP");
	//sym->printCurScope(logout);
	SymbolInfo *s= new  SymbolInfo(yytext, (char *)"BITOP");
	yylval = (YYSTYPE)s;
	return BITOP;
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 509 "1505010.l"
{
	SymbolInfo *s= new  SymbolInfo();
	switch(yytext[0])
	{
	//SymbolInfo *s= new  SymbolInfo();
	case '!' : //printf("<NOT, %s>\n", yytext); 
	fprintf(tokenout,"<NOT,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <NOT> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"NOT");
	s->setName(yytext);
	s->setType((char *)"NOT");
	yylval = (YYSTYPE)s;
	return NOT;
	break;
	
	case '(' : //printf("<LPAREN, %s>\n", yytext); 
	fprintf(tokenout,"<LPAREN,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <LPAREN> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"LAPREN");
	s->setName(yytext);
	s->setType((char *)"LPAREN");
	yylval = (YYSTYPE)s;
	return LPAREN;
	break;
	
	case ')' : //printf("<RPAREN, %s>\n", yytext); 
	fprintf(tokenout,"<RPAREN,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <RPAREN> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"RPAREN");
	s->setName(yytext);
	s->setType((char *)"RPAREN");
	yylval = (YYSTYPE)s;
	return RPAREN;
	break;
	
	case '{' : //printf("<LCURL, %s>\n", yytext); 
	fprintf(tokenout,"<LCURL,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <LCURL> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"LCURL");
	s->setName(yytext);
	s->setType((char *)"LCURL");
	yylval = (YYSTYPE)s;
	//table->enterScope(fp2);
	//sym->enterScope();
	return LCURL;
	break;
	
	case '}' : //printf("<RCURL, %s>\n", yytext); 
	fprintf(tokenout,"<RCURL,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <RCURL> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"RCURL");
	s->setName(yytext);
	s->setType((char *)"RCURL");
	yylval = (YYSTYPE)s;
	//table->printAllScope(fp2);
	//table->exitScope(fp2);
	//sym->exitScope();
	return RCURL;
	break;
	
	case '[' : //printf("<LTHIRD, %s>\n", yytext); 
	fprintf(tokenout,"<LTHIRD,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <LTHIRD> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"LTHIRD");
	s->setName(yytext);
	s->setType((char *)"LTHIRD");
	yylval = (YYSTYPE)s;
	return LTHIRD;
	break;
	
	case ']' : //printf("<RTHIRD, %s>\n", yytext); 
	fprintf(tokenout,"<RTHIRD,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <RTHIRD> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"RTHIRD");
	s->setName(yytext);
	s->setType((char *)"RTHIRD");
	yylval = (YYSTYPE)s;
	return RTHIRD;
	break;
	
	case ',' : //printf("<COMMA, %s>\n", yytext); 
	fprintf(tokenout,"<COMMA,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <COMMA> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"COMMA");
	s->setName(yytext);
	s->setType((char *)"COMMA");
	yylval = (YYSTYPE)s;
	yylval = (YYSTYPE)s;
	return COMMA;
	break;
	
	case ';' : //printf("<SEMICOLON, %s>\n", yytext); 
	fprintf(tokenout,"<SEMICOLON,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <SEMICOLON> Lexeme %s found\n\n",line_num,yytext);
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"SEMICOLON");
	s->setName(yytext);
	s->setType((char *)"SEMICOLON");
	yylval = (YYSTYPE)s;
	return SEMICOLON;
	break;
	
	}
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 613 "1505010.l"
{
	//printf("<%s, INDENTIFIER>\n",yytext);
	fprintf(tokenout,"<ID,%s>  ",yytext);
	fprintf(logout,"Line No. %d: Token <ID> Lexeme %s found\n\n",line_num,yytext);
	/*
	
	if(sym->insert(yytext, "ID"))
		sym->printCurScope(logout);
	//sym->printCurScope(logout);
	
	*/
	//SymbolInfo *s= new  SymbolInfo(yytext, (char *)"ID");
	SymbolInfo *s= table->lookUp(yytext);
	
	if(!s->getName().compare("-1"))
	{	
		//cout << "inside if\n\n";				
		s= new SymbolInfo(yytext, (char *)"ID");
	}
	yylval = (YYSTYPE)s;
	return ID;
	
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 637 "1505010.l"
{
	string_buf_ptr = (char*) malloc(MAX_STR_CONST * sizeof(char));
	tokStr = (char*) malloc(MAX_STR_CONST * sizeof(char));
	strcpy(string_buf_ptr, "\"");
	strcpy(tokStr, "\0");
	prevline = line_num;
	BEGIN(str);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 645 "1505010.l"
{
	/*saw closing quote - all done */

	//printf("<STRING, %s>\n", string_buf_ptr);
	//fprintf(tokenout,"<STRING,%s>  ",string_buf_ptr);
	strcat(string_buf_ptr, "\"");
	fprintf(logout,"Line No. %d: Token <STRING> Lexeme %s found\n\n",prevline,string_buf_ptr);
	fprintf(tokenout,"<STRING, \"%s\">  ",tokStr);
	
	if(string_buf_ptr) free(string_buf_ptr);//='\0';
	if(tokStr) free(tokStr);
	BEGIN(INITIAL);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 658 "1505010.l"
{
	fprintf(logout,"Error at line %d: Unfinished string %s\n\n",line_num,string_buf_ptr);
	error++;
	line_num++;
	if(string_buf_ptr) free(string_buf_ptr);
	if(tokStr) free(tokStr);
	BEGIN(INITIAL);
	//printf("\n\n---error %s error---\n\n", yytext);
        /* error - unterminated string constant */
        /* generate error message */
        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 671 "1505010.l"
{
        /* generate error - bad escape sequence; something
         * like '\48' or '\0777777'
         */
        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 677 "1505010.l"
{
	char *ch =(char*) malloc(sizeof(char)); 
	//ch = "\n"; 
	strcat(string_buf_ptr, "\\n");
	strcat(tokStr, "\n");
	line_num++;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 684 "1505010.l"
{
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "\t"; 
	strcat(string_buf_ptr, "\\t");
	strcat(tokStr, "\t");
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 690 "1505010.l"
{
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "\r"; 
	strcat(string_buf_ptr, "\\r");
	strcat(tokStr, "\r");
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 696 "1505010.l"
{
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "\b"; 
	strcat(string_buf_ptr, "\\b");
	strcat(tokStr, "\b");
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 702 "1505010.l"
{
	char *ch = (char*) malloc(sizeof(char)); 
	//ch = "\f"; 
	strcat(string_buf_ptr, "\\f");
	strcat(tokStr, "\f");
	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 709 "1505010.l"
{
	char *ch = (char*) malloc(sizeof(char)); 
	//ch[0] = yytext[1]; 
	//printf("slash %s newline\n", yytext);
	strcat(string_buf_ptr, yytext);
	if(yytext[2]=='\n' || yytext[1]=='\n') line_num++;
	if(yytext[1]=='\\') {
		strcat(tokStr, "\\");
	}
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 720 "1505010.l"
{
        char *yptr = yytext;
	if(strlen(yptr)+strlen(string_buf_ptr)>MAX_STR_CONST)
	{	
		MAX_STR_CONST += strlen(yptr);
		MAX_STR_CONST*=2;
		string_buf_ptr = (char*) realloc(string_buf_ptr, MAX_STR_CONST);
		tokStr = (char*) realloc(tokStr, MAX_STR_CONST);
	}
	strcat(string_buf_ptr, yptr);
	strcat(tokStr, yptr);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 732 "1505010.l"
{
	//printf("Too many Decimal point error\n");
	//fprintf(tokenout,"<MULOP,%s>\n",yytext);
	fprintf(logout,"Error at line %d: Too many Decimal point %s\n\n",line_num,yytext);
	error++;
	//printf("\n\n---error---\n\n");
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 739 "1505010.l"
{
	//printf("Ill formed number\n");
	fprintf(logout,"Error at line %d: Ill formed number %s\n\n",line_num,yytext);
	error++;
	//printf("\n\n---error---\n\n");
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 745 "1505010.l"
{
	//printf("Invalid Suffix on numeric constant or Invalid prefix on identifier\n");
	fprintf(logout,"Error at line %d: Invalid Suffix on numeric constant or Invalid prefix on identifier %s\n\n",line_num,yytext);
	error++;
	//printf("\n\n---error---\n\n");
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 751 "1505010.l"
{

	fprintf(logout,"Error at line %d: Multi character constant error %s\n\n",line_num,yytext);
	error++;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 757 "1505010.l"
{
	//printf("Multi character constant error\n");
	fprintf(logout,"Error at line %d: Multi character constant error %s\n\n",line_num,yytext);
	error++;
	//printf("\n\n---error---\n\n");
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 764 "1505010.l"
{
		//printf("Unrecognized Character\n"); 
		fprintf(logout,"Error at line %d: Unrecognized Character %s\n\n",line_num,yytext);
		error++;
		//printf("error..\n");
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 771 "1505010.l"
{
	//printf("Unfinished Character\n"); 
	fprintf(logout,"Error at line %d: Unfinished Character %s\n\n",line_num,yytext);
	error++;
	//printf("\n\n---error---\n\n");
	}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(cmnt):
case YY_STATE_EOF(test):
case YY_STATE_EOF(multichar):
#line 777 "1505010.l"
{
	//printf("Total Line Number: %d and word number: %d\n",line_count,word_count); 
	/*
	
	sym->printAllScope(logout);
	
	*/
	fprintf(logout,"Total Lines: %d\n",line_num);
	fprintf(logout,"Total Errors: %d\n",error);
	//printf("error %d\n",error);	
	return 0;
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 790 "1505010.l"
{ strcat(string_buf_ptr, yytext);BEGIN(str);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 791 "1505010.l"
BEGIN(str);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 793 "1505010.l"
ECHO;
	YY_BREAK
#line 1802 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 177 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 177 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 176);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 793 "1505010.l"


int yywrap(void)
{
	return 1;
}


/*
int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	sym = new SymbolTable;
	sym->setCapacity(10);
	
	logout= fopen("1505010_log.txt","w");
	tokenout= fopen("1505010_token.txt","w");

	yyin= fin;
	yylex();
	fclose(yyin);
	fclose(tokenout);
	fclose(logout);
	return 0;
}
*/
